[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:vnc]
command=/usr/bin/Xvnc :1 -geometry %(ENV_VNC_RESOLUTION)s -depth %(ENV_VNC_DEPTH)s -rfbport %(ENV_VNC_PORT)s -SecurityTypes VncAuth -PasswordFile /home/vnc/.vnc/passwd -AlwaysShared -AcceptKeyEvents -AcceptPointerEvents -AcceptSetDesktopSize -SendCutText -AcceptCutText -listen tcp -ac
user=vnc
autorestart=true
stdout_logfile=/var/log/supervisor/vnc.log
stderr_logfile=/var/log/supervisor/vnc_error.log

[program:sshd]
command=/usr/sbin/sshd -D -e
user=root
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd_error.log