[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:vnc]
command=/usr/bin/Xvnc :1 -geometry %(ENV_VNC_RESOLUTION)s -depth %(ENV_VNC_DEPTH)s -rfbport %(ENV_VNC_PORT)s -SecurityTypes VncAuth -PasswordFile /home/vnc/.vnc/passwd -AlwaysShared -AcceptKeyEvents -AcceptPointerEvents -AcceptSetDesktopSize -SendCutText -AcceptCutText -ac
user=vnc
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/vnc.log
stderr_logfile=/var/log/supervisor/vnc_error.log

[program:application]
command=/usr/local/bin/start-x11-application
user=root
priority=20
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/application.log
stderr_logfile=/var/log/supervisor/application_error.log